apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: todo-app

spec:
  type: LoadBalancer

  selector:
    app: todo-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
